/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlite;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import jlite.parser.Ast;
import jlite.parser.parser;

public class App {
    public static void main(String[] argv) {
        for (String fileLoc : argv) {
            try {
                Gson gson = new GsonBuilder()
                        .setPrettyPrinting()
                        .create();
                Ast.Program program = parser.parse(fileLoc);
                System.out.println(gson.toJson(program));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
